[project]
name = "numba_cuda"
version = "0.1.0"
description = "CUDA target for Numba"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Anaconda Inc." },
    { name = "NVIDIA Corporation" }
]
license = { text = "BSD 2-clause" }
requires-python = ">=3.9"
